List out which remote branches could not be deleted

diff --git a/git/commands/git-spring-clean b/git/commands/git-spring-clean
--- a/git/commands/git-spring-clean
+++ b/git/commands/git-spring-clean
@@ -25,3 +25,10 @@ git branch -r |
   grep -v "/production$" |
   grep -v "/green$" |
   xargs git branch -d -r
+
+
+if [ $? -ne 0 ]; then
+  echo ''
+  echo -e "$CYAN- remote branch nuke failed, manually delete these: -$CLEAR"
+  git branch -r | grep \'
+fi
